language: node_js
node_js:
  - 9
  - 8

cache:
  directories:
    - ~/.npm
notifications:
  email: false

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run travis-deploy-once "npm run semantic-release"
